-dontwarn java.awt.**
-dontwarn javax.swing.**
-dontwarn org.openstreetmap.josm.plugins.hexgrid.HexGridSideInputDialog
-dontobfuscate
-dontoptimize
-keep class org.openstreetmap.josm.plugins.hexgrid.**